### ISSUE TITLE
Implement generic version of cdf  for primarydist

### ISSUE THREAD

**Issue by medewitt** [epinowcast/PrimaryCensored.jl#15]
Translate Sam Brand's work from EpiAware as a method for primarycensored.

https://github.com/CDCgov/Rt-without-renewal/blob/03a400116be5dd4516dacaa4c20fcdb0590a0f1d/EpiAware/src/EpiAwareUtils/censored_pmf.jl

**Comment by SamuelBrand1** [comment]
I actually split that up even further this morning to make it easier to deal with different width censor windows. This link is code pretty specialised to primary _and_ secondary window being the same length and windows coming as a disjoint cover of the time period.

https://github.com/CDCgov/Rt-without-renewal/blob/primary-cens-example/EpiAware/src/EpiAwareUtils/censored_pmf.jl

Although I'm having my doubts that exporting a function with name `∫F` is a wise decision.

**Comment by seabbs** [comment]
I think I did this on the last day of the collab
